/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./../src/components/BarChart.vue')['default']
    CryptoCard: typeof import('./../src/components/CryptoCard.vue')['default']
    CryptoTable: typeof import('./../src/components/CryptoTable.vue')['default']
    CustomerForm: typeof import('./../src/components/CustomerForm.vue')['default']
    CustomerTable: typeof import('./../src/components/CustomerTable.vue')['default']
    DateInput: typeof import('./../src/components/DateInput.vue')['default']
    InvoiceTable: typeof import('./../src/components/InvoiceTable.vue')['default']
    LineChart: typeof import('./../src/components/LineChart.vue')['default']
    PaymentForm: typeof import('./../src/components/PaymentForm.vue')['default']
    PieChart: typeof import('./../src/components/pieChart.vue')['default']
    QuotationTable: typeof import('./../src/components/quotationTable.vue')['default']
    RevenuTable: typeof import('./../src/components/revenuTable.vue')['default']
    SignInForm: typeof import('./../src/components/signInForm.vue')['default']
    SignUpForm: typeof import('./../src/components/signUpForm.vue')['default']
    TotalField: typeof import('./../src/components/totalField.vue')['default']
    Weather: typeof import('./../src/components/weather.vue')['default']
  }
}
