/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./../src/components/general/barChart.vue')['default']
    CryptoCard: typeof import('./../src/components/crypto/cryptoCard.vue')['default']
    CryptoTable: typeof import('./../src/components/crypto/cryptoTable.vue')['default']
    CustomerForm: typeof import('./../src/components/customer/customerForm.vue')['default']
    CustomerTable: typeof import('./../src/components/customer/customerTable.vue')['default']
    InvoiceTable: typeof import('./../src/components/invoice/invoiceTable.vue')['default']
    LineChart: typeof import('./../src/components/general/lineChart.vue')['default']
    PaymentForm: typeof import('./../src/components/general/paymentForm.vue')['default']
    PieChart: typeof import('./../src/components/general/pieChart.vue')['default']
    QuotationTable: typeof import('./../src/components/quotation/quotationTable.vue')['default']
    RevenuTable: typeof import('./../src/components/revenu/revenuTable.vue')['default']
    SignInForm: typeof import('./../src/components/auth/signInForm.vue')['default']
    SignUpForm: typeof import('./../src/components/auth/signUpForm.vue')['default']
    TotalField: typeof import('./../src/components/general/totalField.vue')['default']
    Weather: typeof import('./../src/components/general/weather.vue')['default']
  }
}
