/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AssetModal: typeof import('./../src/components/AssetModal.vue')['default']
    AssetTable: typeof import('./../src/components/AssetTable.vue')['default']
    BankModal: (typeof import("./../src/components/BankModal.vue"))["default"]
    BarChart: typeof import('./../src/components/BarChart.vue')['default']
    CryptoCard: typeof import('./../src/components/CryptoCard.vue')['default']
    CryptoTable: typeof import('./../src/components/CryptoTable.vue')['default']
    CustomerForm: typeof import('./../src/components/CustomerForm.vue')['default']
    CustomerTable: typeof import('./../src/components/CustomerTable.vue')['default']
    DateInput: typeof import('./../src/components/DateInput.vue')['default']
    InvoiceTable: typeof import('./../src/components/InvoiceTable.vue')['default']
    LineChart: typeof import('./../src/components/LineChart.vue')['default']
    NumberInput: typeof import('./../src/components/NumberInput.vue')['default']
    PaymentForm: typeof import('./../src/components/PaymentForm.vue')['default']
    PendingEmailForm: typeof import('./../src/components/PendingEmailForm.vue')['default']
    PieChart: typeof import('./../src/components/PieChart.vue')['default']
    QuotationTable: typeof import('./../src/components/QuotationTable.vue')['default']
    RevenuTable: typeof import('./../src/components/RevenuTable.vue')['default']
    SignInForm: typeof import('./../src/components/SignInForm.vue')['default']
    SignUpForm: typeof import('./../src/components/SignUpForm.vue')['default']
    TotalField: typeof import('./../src/components/TotalField.vue')['default']
    Weather: typeof import('./../src/components/Weather.vue')['default']
  }
}
