-- AlterTable
ALTER TABLE
  "Credits"
ADD
  COLUMN "recurrent" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE
  "Revenus"
ADD
  COLUMN "average_costs" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD
  COLUMN "average_credits" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD
  COLUMN "balance" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD
  COLUMN "investment_capacity" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD
  COLUMN "investments" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD
  COLUMN "recurrent_costs" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD
  COLUMN "recurrent_credits" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD
  COLUMN "tax_amount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD
  COLUMN "total_costs" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD
  COLUMN "total_credits" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD
  COLUMN "total_net" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD
  COLUMN "tva_balance" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE
  "Users"
ADD
  COLUMN "investment_goal" DOUBLE PRECISION NOT NULL DEFAULT 0.2,
ADD
  COLUMN "withholding_tax_active" BOOLEAN NOT NULL DEFAULT true;