ALTER TABLE "Customers"
  ADD "UserId" INTEGER DEFAULT NULL,
  ADD CONSTRAINT "fk_customer_user" FOREIGN KEY ("UserId") REFERENCES "Users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "Banks"
  ADD "UserId" INTEGER DEFAULT NULL,
  ADD CONSTRAINT "fk_bank_user" FOREIGN KEY ("UserId") REFERENCES "Users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "CryptoCurrencies"
  ADD "UserId" INTEGER DEFAULT NULL,
  ADD CONSTRAINT "fk_crypto_currency_user" FOREIGN KEY ("UserId") REFERENCES "Users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;